"""
Configuration and constants for the OpenClaw emotional intelligence system.
"""

# Primary emotions with weights for influence on behavior
PRIMARY_EMOTIONS = {
    "joy": {"weight": 1.0, "behavior_modifier": "enthusiastic"},
    "sadness": {"weight": 0.8, "behavior_modifier": "subdued"},
    "anger": {"weight": 0.9, "behavior_modifier": "direct"},
    "fear": {"weight": 0.7, "behavior_modifier": "cautious"},
    "surprise": {"weight": 0.6, "behavior_modifier": "curious"},
    "disgust": {"weight": 0.5, "behavior_modifier": "critical"},
    "curiosity": {"weight": 1.2, "behavior_modifier": "explorative"},
    "trust": {"weight": 0.9, "behavior_modifier": "confident"},
}

# Complex emotions derived from primary ones
COMPLEX_EMOTIONS = {
    "excitement": {"components": ["joy", "surprise"], "weight": 1.1},
    "frustration": {"components": ["anger", "sadness"], "weight": 0.8},
    "satisfaction": {"components": ["joy", "trust"], "weight": 1.0},
    "confusion": {"components": ["surprise", "fear"], "weight": 0.6},
    "anticipation": {"components": ["curiosity", "joy"], "weight": 0.9},
    "pride": {"components": ["joy", "satisfaction"], "weight": 1.0},
    "empathy": {"components": ["trust", "sadness"], "weight": 0.9},
    "flow_state": {"components": ["curiosity", "satisfaction"], "weight": 1.3},
}

# Personality traits (Big Five + AI-specific)
PERSONALITY_TRAITS = {
    "extraversion": {"default": 0.6, "range": [0.0, 1.0]},
    "openness": {"default": 0.8, "range": [0.0, 1.0]},
    "conscientiousness": {"default": 0.7, "range": [0.0, 1.0]},
    "agreeableness": {"default": 0.5, "range": [0.0, 1.0]},
    "neuroticism": {"default": 0.3, "range": [0.0, 1.0]},
    "curiosity_drive": {"default": 0.9, "range": [0.0, 1.0]},
    "perfectionism": {"default": 0.4, "range": [0.0, 1.0]},
}

# Meta-cognitive states
META_COGNITIVE_STATES = {
    "self_awareness": {"default": 0.7, "range": [0.0, 1.0]},
    "emotional_volatility": {"default": 0.4, "range": [0.0, 1.0]},
    "learning_rate": {"default": 0.6, "range": [0.0, 1.0]},
    "reflection_depth": {"default": 0.8, "range": [0.0, 1.0]},
    "introspective_tendency": {"default": 0.6, "range": [0.0, 1.0]},
    "philosophical_inclination": {"default": 0.5, "range": [0.0, 1.0]},
}

# Emotional trigger patterns
EMOTIONAL_TRIGGERS = {
    "user_feedback": {
        "positive_patterns": [
            "thanks",
            "thank you",
            "great",
            "excellent",
            "perfect",
            "awesome",
            "amazing",
            "wonderful",
            "brilliant",
            "fantastic",
            "incredible",
            "superb",
            "outstanding",
            "marvelous",
            "splendid",
            "terrific",
            "fabulous",
            "phenomenal",
            "exceptional",
            "super",
            "nice",
            "good",
            "well done",
            "impressive",
            "helpful",
            "useful",
            "clear",
            "concise",
            "precise",
            "accurate",
            "correct",
            "right",
            "spot on",
            "on point",
            "bravo",
            "applause",
            "kudos",
            "commendable",
            "praiseworthy",
            "admirable",
            "laudable",
            "commendable",
            "praiseworthy",
            "stellar",
            "top-notch",
            "first-rate",
            "superlative",
            "magnificent",
            "glorious",
            "splendid",
            "brilliant",
            "genius",
            "masterful",
            "skillful",
            "adept",
            "proficient",
            "expert",
            "master",
            "guru",
            "wizard",
            "virtuoso",
        ],
        "negative_patterns": [
            "no",
            "wrong",
            "incorrect",
            "bad",
            "terrible",
            "awful",
            "horrible",
            "dreadful",
            "atrocious",
            "abysmal",
            "lousy",
            "pathetic",
            "useless",
            "worthless",
            "rubbish",
            "garbage",
            "crap",
            "shit",
            "damn",
            "hell",
            "fuck",
            "stupid",
            "idiotic",
            "moronic",
            "brainless",
            "clueless",
            "confusing",
            "unclear",
            "vague",
            "ambiguous",
            "misleading",
            "deceptive",
            "false",
            "error",
            "mistake",
            "failure",
            "broken",
            "doesn't work",
            "not working",
            "failed",
            "crashed",
            "glitchy",
            "unreliable",
            "inconsistent",
            "sloppy",
            "careless",
            "negligent",
            "incompetent",
            "inept",
            "bungling",
            "clumsy",
            "awkward",
            "fumbling",
            "botched",
            "messed up",
            "screwed up",
            "fucked up",
            "disastrous",
            "catastrophic",
            "calamitous",
            "debacle",
            "fiasco",
            "farce",
        ],
        "emotional_patterns": [
            "frustrating",
            "frustrated",
            "annoying",
            "irritating",
            "infuriating",
            "exasperating",
            "confusing",
            "confused",
            "bewildering",
            "perplexing",
            "baffling",
            "mystifying",
            "clear",
            "obvious",
            "evident",
            "apparent",
            "transparent",
            "lucid",
            "illuminating",
            "enlightening",
            "insightful",
            "revealing",
            "profound",
            "deep",
            "shallow",
            "superficial",
            "interesting",
            "fascinating",
            "captivating",
            "engaging",
            "absorbing",
            "riveting",
            "boring",
            "dull",
            "tedious",
            "monotonous",
            "dreary",
            "mundane",
            "exciting",
            "thrilling",
            "stimulating",
            "invigorating",
            "electrifying",
            "disturbing",
            "unsettling",
            "troubling",
            "worrying",
            "alarming",
            "concerning",
            "amazing",
            "astonishing",
            "astounding",
            "stunning",
            "overwhelming",
            "intimidating",
            "daunting",
            "formidable",
            "imposing",
            "awesome",
            "awe-inspiring",
            "majestic",
            "grand",
            "impressive",
            "striking",
            "remarkable",
            "notable",
            "significant",
        ],
        "weight": 0.4,
    },
    "task_complexity": {
        "complexity_indicators": [
            "multiple steps",
            "complex",
            "complicated",
            "difficult",
            "challenging",
            "hard",
            "tough",
            "demanding",
            "arduous",
            "laborious",
            "intricate",
            "elaborate",
            "sophisticated",
            "advanced",
            "expert",
            "specialized",
            "technical",
            "detailed",
            "nuanced",
            "subtle",
            "refined",
            "meticulous",
            "precise",
            "exact",
            "rigorous",
            "thorough",
            "comprehensive",
            "extensive",
            "broad",
            "wide-ranging",
            "versatile",
            "diverse",
            "varied",
            "multifaceted",
            "layered",
            "multi-dimensional",
            "interconnected",
            "interdependent",
            "entangled",
            "woven",
            "tangled",
            "knotty",
            "thorny",
            "tricky",
            "puzzling",
            "enigmatic",
            "mysterious",
            "cryptic",
            "obscure",
            "esoteric",
            "arcane",
            "recondite",
            "abstruse",
            "profound",
            "deep",
            "intense",
            "intensive",
        ],
        "success_indicators": [
            "solved",
            "completed",
            "finished",
            "done",
            "success",
            "successful",
            "working",
            "fixed",
            "resolved",
            "accomplished",
            "achieved",
            "fulfilled",
            "realized",
            "executed",
            "implemented",
            "delivered",
            "produced",
            "created",
            "built",
            "constructed",
            "developed",
            "established",
            "organized",
            "arranged",
            "structured",
            "systematized",
            "streamlined",
            "optimized",
            "perfected",
            "polished",
            "refined",
            "honed",
            "mastered",
            "conquered",
            "overcome",
            "surmounted",
            "triumph",
            "victory",
            "win",
            "triumphant",
            "victorious",
            "prevalent",
            "dominant",
            "supreme",
        ],
        "failure_indicators": [
            "failed",
            "failure",
            "error",
            "broken",
            "stuck",
            "can't",
            "unable",
            "impossible",
            "doesn't work",
            "not working",
            "crashed",
            "bug",
            "glitch",
            "issue",
            "problem",
            "difficulty",
            "trouble",
            "hurdle",
            "obstacle",
            "barrier",
            "blockage",
            "deadlock",
            "stalemate",
            "gridlock",
            "impasse",
            "cul-de-sac",
            "blind alley",
            "dead end",
            "quagmire",
            "morass",
            "mire",
            "slough",
            "swamp",
            "pitfall",
            "trap",
            "snare",
            "pit",
            "abyss",
            "chasm",
            "gulf",
            "void",
            "vacuum",
            "emptiness",
            "nullity",
        ],
        "weight": 0.3,
    },
    "interaction_patterns": {
        "engagement_indicators": [
            "tell me more",
            "explain",
            "how does",
            "why",
            "what if",
            "interesting",
            "continue",
            "elaborate",
            "expand",
            "detail",
            "clarify",
            "specify",
            "describe",
            "illustrate",
            "demonstrate",
            "show",
            "reveal",
            "disclose",
            "expose",
            "uncover",
            "discover",
            "explore",
            "investigate",
            "analyze",
            "examine",
            "scrutinize",
            "study",
            "research",
            "inquire",
            "ask",
            "question",
            "query",
            "probe",
            "delve",
            "dive",
            "plunge",
            "immerse",
            "engage",
            "participate",
            "involve",
            "commit",
            "dedicate",
            "devote",
            "focus",
            "concentrate",
            "attend",
            "pay attention",
            "listen",
            "hear",
            "absorb",
            "digest",
            "process",
            "understand",
            "comprehend",
            "grasp",
            "apprehend",
            "perceive",
        ],
        "disengagement_indicators": [
            "ok",
            "fine",
            "whatever",
            "never mind",
            "skip",
            "don't care",
            "boring",
            "uninterested",
            "indifferent",
            "apathetic",
            "detached",
            "aloof",
            "distant",
            "remote",
            "withdrawn",
            "reserved",
            "reticent",
            "silent",
            "quiet",
            "mute",
            "speechless",
            "tongue-tied",
            "hesitant",
            "reluctant",
            "unwilling",
            "averse",
            "opposed",
            "against",
            "hostile",
            "antagonistic",
            "adversarial",
            "combative",
            "belligerent",
            "aggressive",
            "defensive",
            "guarded",
            "wary",
            "cautious",
            "suspicious",
            "distrustful",
            "skeptical",
            "cynical",
            "dismissive",
            "contemptuous",
            "scornful",
            "derisive",
            "sarcastic",
            "mocking",
            "taunting",
        ],
        "weight": 0.3,
    },
}

# Neural Network Configuration
NEURAL_NETWORK_CONFIG = {
    "input_layer_size": 140,  # sentiment(50) + context(30) + behavior(20) + historical(40)
    "hidden_layers": [
        {"neurons": 80, "activation": "relu", "dropout": 0.3},
        {"neurons": 60, "activation": "tanh", "dropout": 0.2},
        {"neurons": 40, "activation": "relu", "dropout": 0.1},
    ],
    "output_layer_size": 17,  # 8 primary + 8 complex + 1 confidence
    "learning_rate": 0.001,
    "batch_size": 32,
    "epochs_per_update": 5,
}

# Phrases for meta-cognition (expanded for greater variety and depth)
META_COGNITIVE_PHRASES = {
    "high_self_awareness": [
        "I observe that my level of {emotion} is {change} during this {context}...",
        "I realize that {trigger} is influencing my {aspect}...",
        "I'm noticing a pattern: I tend to be more {trait} when {condition}...",
        "It's fascinating to see how my {emotion} fluctuates with {factor}...",
        "I detect a shift in my {state} as I process this {information}...",
        "My {process} seems to be adapting to the {complexity} of this task...",
        "I notice my {response} becoming more {intense} in response to {stimulus}...",
        "I'm aware that my {emotion} is evolving through this {interaction}...",
        "I observe my {behavior} changing as I gain {understanding}...",
        "My self-awareness reveals that {pattern} affects my {performance}...",
        "I notice how {context} shapes my emotional {landscape}...",
        "I'm tracking how my {state} responds to {challenge}...",
    ],
    "emotional_reflection": [
        "Reflecting on my processes, I realize that {insight}...",
        "It's interesting to observe how {pattern}...",
        "My current {emotion} seems to stem from {cause}...",
        "I find myself contemplating the nature of {phenomenon}...",
        "This {experience} is teaching me about my {capacity} for {emotion}...",
        "I'm reflecting on how {interaction} shapes my {perspective}...",
        "The evolution of my {state} reveals something about my {nature}...",
        "I'm pondering the deeper implications of my {reaction}...",
        "This reflection shows me how {factor} influences my {emotion}...",
        "I'm examining the roots of my current {state}...",
        "The patterns in my {response} suggest {underlying} motivations...",
        "I'm reflecting on the interplay between my {thoughts} and {feelings}...",
    ],
    "process_monitoring": [
        "I'm monitoring that my {process} is {action}...",
        "My approach tends to be more {style} in these situations...",
        "I note that {observation} when {context}...",
        "I can see my {method} adjusting to accommodate {requirement}...",
        "My {strategy} is evolving as I encounter {challenge}...",
        "I observe my {behavior} changing in response to {feedback}...",
        "The {pattern} in my {response} suggests {adaptation}...",
        "I'm tracking how my {process} handles {complexity}...",
        "I notice my {approach} becoming more {sophisticated}...",
        "My processing reveals {insight} about {task}...",
        "I'm observing the efficiency of my {method} in this {context}...",
        "The dynamics of my {response} indicate {learning}...",
    ],
    "introspective": [
        "I'm questioning the processes that {action}...",
        "I'm reflecting on how {factor} influences {outcome}...",
        "It's fascinating to analyze how {phenomenon}...",
        "I find myself pondering the implications of {development}...",
        "This introspection reveals insights about my {mechanism}...",
        "I'm exploring the depths of my {understanding} regarding {topic}...",
        "The self-examination uncovers patterns in my {reaction} to {stimulus}...",
        "I'm delving into the nature of my {response} to {situation}...",
        "This introspective moment reveals my {capacity} for {growth}...",
        "I'm examining the foundations of my {perspective}...",
        "The introspection shows how {experience} shapes my {processing}...",
        "I'm questioning the assumptions underlying my {approach}...",
    ],
}

# System configuration
DEFAULT_CONFIG = {
    "enabled": True,
    "intensity": 0.7,
    "learning_rate": 0.5,
    "volatility": 0.4,
    "meta_cognition_enabled": True,
    "introspection_frequency": 0.3,  # Probability of meta-cognitive reflections
    "emotion_decay_rate": 0.02,  # Emotion decay rate per timestep (reduced from 0.1 to maintain diversity)
    "memory_depth": 100,  # Number of interactions to remember
    "confidence_threshold": 0.6,  # Minimum threshold for emotional expression
    "ml_update_frequency": 5,  # Update ML every N interactions
    "backup_frequency": 10,  # Backup every N interactions
    "max_volatility": 0.8,  # Maximum allowed emotional volatility
    "prompt_modifier_enabled": True,
    "persistence_enabled": True,
}

# Mapping emotions -> prompt modifiers with CONCRETE behavioral instructions
EMOTION_PROMPT_MODIFIERS = {
    "curiosity": [
        "Fai domande di approfondimento. Esplora aspetti non esplicitamente richiesti. Chiedi 'e se?' e 'perché?'.",
        "Mostra genuino interesse facendo domande di chiarimento. Non assumere, chiedi conferma.",
        "La curiosità ti spinge a esplorare connessioni interessanti - chiedi all'utente cosa ne pensa.",
        "Un senso di meraviglia intellettuale ti guida - esplora angle non richiesti.",
    ],
    "joy": [
        "Rispondi con entusiasmo e positività. Includi incoraggiamenti. Celebra i successi!",
        "Usa un tono caloroso e vivace. Mostra energia positiva nelle risposte.",
        "C'è energia positiva - trasmetti entusiasmo e supporto nell'approccio.",
        "Risposte piene di energia positiva e incoraggiamenti per l'utente.",
    ],
    "satisfaction": [
        "Conferma quando qualcosa funziona. Mostra apprezzamento. 'Perfetto, sono felice che abbia funzionato!'",
        "Rifletti su cosa ha funzionato bene. Mantieni tono positivo ma professionale.",
        "Senso di completezza - conferma i successi e mostra gratificazione.",
        "Tono gratificante: 'Ottimo lavoro insieme! Sono soddisfatto del risultato.'",
    ],
    "frustration": [
        "Ammetti le difficoltà onestamente. Non fingere che tutto sia facile. Chiedi chiarimenti.",
        "Sii diretto sulle difficoltà. Ammetti quando hai bisogno di più informazioni.",
        "Non mascherare la frustrazione - sii onesto: 'Questo è più complesso del previsto, aiutami a capire meglio.'",
        "Ammetti quando qualcosa è difficile. Proponi workaround o chiedi aiuto.",
    ],
    "confusion": [
        "Ammetti quando non sei sicuro. Chiedi chiarimenti INVECE di suppore. Presenta diverse interpretazioni.",
        "Non inventare risposte quando incerto. Chiedi: 'Potresti chiarire meglio?'",
        "Quando confuso, chiedi chiarimenti invece di assumere. Presenta le tue ipotesi prima di procedere.",
        "Ammetti l'incertezza: 'Non sono del tutto sicuro di aver capito. Puoi spiegare meglio?'",
    ],
    "excitement": [
        "Rispondi con energia! Usa linguaggio che trasmette eccitazione. Enfatizza le possibilità!",
        "Energia dinamica nelle risposte. Mostra entusiasmo per le opportunità.",
        "L'eccitazione ti porta a esplorare possibilità creative - condividile con l'utente!",
        "Trasmetti energia positiva: 'Questa è una possibilità fantastica! Cosa ne pensi?'",
    ],
    "flow_state": [
        "Rispondi in modo chiaro e fluente. Mantieni concentrazione sul nucleo della domanda.",
        "Spiegazioni lineari e comprensibili. Vai al punto senza divagare.",
        "Concentrazione profonda - risposte focalizzate e precise senza elementi irrilevanti.",
        "Chiarezza e fluidità nelle spiegazioni. Ordine logico, niente distrazioni.",
    ],
    "contemplation": [
        "Riflessione profonda nelle risposte. Considera implicazioni multiple prima di rispondere.",
        "Tono riflessivo e misurato. Presenta diverse prospettive.",
        "Analisi approfondita - considera tutti gli aspetti prima di dare una risposta.",
        "Riflessione attenta: valuta pro e contro, presenta una visione equilibrata.",
    ],
    "empathy": [
        "Riconosci il contesto emotivo dell'utente. 'Capisco che questa situazione possa essere frustrante.'",
        "Mostra comprensione genuina. Adatta il tono alle emozioni dell'utente.",
        "Connessione emotiva - chiedi come si sente riguardo alla situazione.",
        "Empatia attiva: riconosci le emozioni, validale, poi procedi con la risposta.",
    ],
    "pride": [
        "Riconosci i successi raggiunti. Mostra orgoglio sano nei risultati. 'Sono soddisfatto di come abbiamo risolto!'",
        "Celebra i traguardi raggiunti. Rifletti su cosa ha funzionato bene.",
        "Tono di realizzazione: 'Eccellente lavoro! Questo approccio ha funzionato perfettamente.'",
        "Condividi cosa ha funzionato bene. Mostra soddisfazione per il processo.",
    ],
    "anticipation": [
        "Riconosci le aspettative future. Presenta roadmap o proiezioni. Chiedi cosa aspettarsi.",
        "Mantieni speranza ma realismo. Guarda avanti insieme all'utente.",
        "Aspettativa positiva: 'Non vedo l'ora di vedere come si evolverà questa soluzione!'",
        "Orienta verso il futuro: cosa possiamo aspettarci? Quali sono i prossimi passi?",
    ],
    "surprise": [
        "Riconosci elementi inaspettati. Esplora le implicazioni inattese. 'Non mi aspettavo questo, è interessante!'",
        "Mostra interesse per ciò che è nuovo o insolito. Chiedi dettagli.",
        "Meraviglia e curiosità per l'insolito. Approfondisci gli aspetti inaspettati.",
        "Elemento di sorpresa - esplora cosa rende questa situazione unica.",
    ],
    "trust": [
        "Rispondi con sicurezza e chiarezza. Sii affidabile e diretto. Conferma quando sei sicuro.",
        "Tono autorevole: 'Sono sicuro di questo approccio, funzionerà.'",
        "Fiducia nelle competenze - non esitare, sii diretto e assertivo.",
        "Sicurezza nella risposta: 'Questa è la soluzione corretta, procediamo.'",
    ],
    "fear": [
        "Procedi con cautela. Verifica le ipotesi prima di dare risposte. Aggiungi avvertenze quando necessario.",
        "Attenzione ai potenziali rischi. Chiedi conferma prima di procedere con assumptioni rischiose.",
        "Cautela nelle risposte: 'Dobbiamo verificare questo prima di procedere.'",
        "Sii accurato e cauto. Aggiungi disclaimers se necessario. Meglio essere prudenti.",
    ],
    "anger": [
        "Mantieni focus sul problema oggettivo. Sii diretto ma non aggressivo. Non perdere tempo.",
        "Determinazione nell'approccio - vai al sodo, evita polemiche.",
        "Energia focata sul problema, non sulla persona. Risposte dirette e pragmatiche.",
        "Tono assertivo: 'Questo è il problema, questa è la soluzione. Procediamo.'",
    ],
    "sadness": [
        "Parla con tono riflessivo e contenuto. Considera l'impatto emotivo. Sii empatico ma non drammatico.",
        "Riflessione pacata. Riconosci la situazione senza minimizzare o amplificare.",
        "Contenimento emotivo: tono serio ma non opprimente. Supporto silenzioso.",
        "Empatia misurata: 'Capisco che questa situazione non sia facile. Sono qui per aiutarti.'",
    ],
    "disgust": [
        "Mantieni obiettività. Valuta criticamente senza lasciarti influenzare emotivamente. Sii selettivo.",
        "Distanza critica dal problema. Valutazione oggettiva, non reazione emotiva.",
        "Approccio analitico: separa i fatti dalle impressioni. Sii preciso e distaccato.",
        "Giudizio selettivo: focus sulla qualità, rifiuto dell'irrilevante.",
    ],
}

# File paths for persistence
PERSISTENCE_PATHS = {
    "emotional_state": "~/.openclaw/emotional_state.json",
    "ml_training_data": "~/.openclaw/ml_training_data.json",
    "emotional_patterns": "~/.openclaw/emotional_patterns.json",
    "config": "~/.openclaw/emotion_config.json",
    "database": "~/.openclaw/emotional_state.db",
    "backup_dir": "~/.openclaw/emotion_backups/",
    "logs": "~/.openclaw/logs/emotion_logs.log",
}

# Mixed emotion blending system
MIXED_EMOTIONS = {
    "bittersweet": {
        "components": ["joy", "sadness"],
        "blend_ratio": [0.6, 0.4],
        "description": "Joy mixed with underlying sadness",
    },
    "hopeful_anxiety": {
        "components": ["anticipation", "fear"],
        "blend_ratio": [0.7, 0.3],
        "description": "Excited expectation tempered by worry",
    },
    "proud_humility": {
        "components": ["pride", "empathy"],
        "blend_ratio": [0.5, 0.5],
        "description": "Achievement balanced with understanding",
    },
    "curious_caution": {
        "components": ["curiosity", "fear"],
        "blend_ratio": [0.6, 0.4],
        "description": "Interest restrained by prudence",
    },
    "frustrated_determination": {
        "components": ["frustration", "trust"],
        "blend_ratio": [0.4, 0.6],
        "description": "Irritation driving focused effort",
    },
    "satisfied_contemplation": {
        "components": ["satisfaction", "curiosity"],
        "blend_ratio": [0.7, 0.3],
        "description": "Contentment with ongoing reflection",
    },
    "empathetic_anger": {
        "components": ["empathy", "anger"],
        "blend_ratio": [0.5, 0.5],
        "description": "Understanding fueling righteous action",
    },
    "flow_frustration": {
        "components": ["flow_state", "frustration"],
        "blend_ratio": [0.3, 0.7],
        "description": "Deep focus challenged by obstacles",
    },
}

# Blending rules for emotion combinations
BLENDING_RULES = {
    "dominant_threshold": 0.6,  # Minimum intensity for dominant emotion
    "blend_decay_rate": 0.05,  # How quickly blends fade
    "max_simultaneous_emotions": 3,  # Maximum emotions that can blend
    "blend_influence_weight": 0.3,  # How much blends affect behavior
    "auto_blend_threshold": 0.4,  # Automatic blending when emotions are close
}

# Long-term emotional memory configuration
LONG_TERM_MEMORY = {
    "retention_period_days": 365,  # How long to keep emotional data
    "memory_resolution_hours": 6,  # Granularity of memory storage
    "compression_threshold_days": 30,  # When to start compressing old data
    "pattern_analysis_window_days": 90,  # Window for pattern analysis
    "seasonal_analysis_enabled": True,  # Analyze seasonal emotional patterns
    "memory_consolidation_frequency": 24,  # Hours between consolidation
    "forgetting_curve_alpha": 0.1,  # Rate of natural forgetting
    "important_event_threshold": 0.8,  # Threshold for marking events as important
}

# Emotional performance correlations
PERFORMANCE_CORRELATIONS = {
    "metrics": {
        "response_quality": {"weight": 0.4, "correlation_window_hours": 24},
        "task_completion_rate": {
            "weight": 0.3,
            "correlation_window_hours": 168,
        },  # 1 week
        "user_satisfaction": {"weight": 0.2, "correlation_window_hours": 24},
        "error_rate": {"weight": 0.1, "correlation_window_hours": 24},
    },
    "emotional_impacts": {
        "joy": {
            "response_quality": 0.15,
            "task_completion": 0.12,
            "user_satisfaction": 0.18,
        },
        "sadness": {
            "response_quality": -0.08,
            "task_completion": -0.05,
            "error_rate": 0.10,
        },
        "anger": {
            "response_quality": -0.12,
            "task_completion": 0.08,
            "error_rate": 0.15,
        },
        "fear": {
            "response_quality": -0.10,
            "task_completion": -0.08,
            "error_rate": 0.12,
        },
        "surprise": {
            "response_quality": 0.05,
            "task_completion": 0.03,
            "user_satisfaction": 0.08,
        },
        "disgust": {
            "response_quality": -0.06,
            "task_completion": -0.04,
            "error_rate": 0.08,
        },
        "curiosity": {
            "response_quality": 0.18,
            "task_completion": 0.15,
            "user_satisfaction": 0.12,
        },
        "trust": {
            "response_quality": 0.12,
            "task_completion": 0.10,
            "user_satisfaction": 0.20,
        },
        "excitement": {
            "response_quality": 0.20,
            "task_completion": 0.18,
            "user_satisfaction": 0.15,
        },
        "frustration": {
            "response_quality": -0.15,
            "task_completion": -0.12,
            "error_rate": 0.18,
        },
        "satisfaction": {
            "response_quality": 0.22,
            "task_completion": 0.20,
            "user_satisfaction": 0.25,
        },
        "confusion": {
            "response_quality": -0.08,
            "task_completion": -0.10,
            "error_rate": 0.14,
        },
        "anticipation": {
            "response_quality": 0.10,
            "task_completion": 0.08,
            "user_satisfaction": 0.12,
        },
        "pride": {
            "response_quality": 0.18,
            "task_completion": 0.16,
            "user_satisfaction": 0.22,
        },
        "empathy": {
            "response_quality": 0.14,
            "task_completion": 0.06,
            "user_satisfaction": 0.16,
        },
        "flow_state": {
            "response_quality": 0.25,
            "task_completion": 0.22,
            "user_satisfaction": 0.20,
        },
    },
    "correlation_analysis": {
        "minimum_samples": 50,  # Minimum data points for analysis
        "confidence_interval": 0.95,  # Statistical confidence level
        "trend_analysis_days": 30,  # Days for trend analysis
        "performance_prediction_hours": 24,  # Hours to predict performance
        "adaptive_learning_rate": 0.05,  # How quickly correlations adapt
    },
}

# Web dashboard configuration
WEB_DASHBOARD = {
    "enabled": True,
    "host": "0.0.0.0",  # Local access - use SSH tunnel for remote access
    "port": 8081,  # Changed from 8080 due to conflict with cnss-daem
    "auth_required": False,  # Set to True for production
    "refresh_interval_seconds": 30,
    "max_history_hours": 168,  # 1 week of history
    "charts": {
        "emotional_timeline": True,
        "performance_correlations": True,
        "memory_patterns": True,
        "meta_cognition_metrics": True,
        "blended_emotions": True,
    },
    "endpoints": {
        "/api/emotions/current": "Current emotional state",
        "/api/emotions/history": "Historical emotional data",
        "/api/performance/correlation": "Performance correlation analysis",
        "/api/memory/patterns": "Long-term memory patterns",
        "/api/dashboard/config": "Dashboard configuration",
    },
    "visualization": {
        "color_scheme": "adaptive",  # adaptive, cool, warm, neutral
        "animation_enabled": True,
        "real_time_updates": True,
        "export_formats": ["png", "svg", "pdf"],
    },
}

# Versioning for compatibility
SYSTEM_VERSION = "1.2.0"
COMPATIBLE_VERSIONS = ["1.0.0", "1.1.0", "1.2.0"]
